# This is a basic workflow to help you get started with Actions

name: Automatic packaging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: |
          tar cfz NHK.tar.gz *
          mv NHK.tar.gz NHK.streams
          
      - name: Get date & time
        run: echo "DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        
      - name: Create a release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            NHK.streams
          tag_name: release-${{ env.DATE }}
          
